language: python

dist: xenial

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -e .[test]

script:
  - python -m pytest --color=yes --cov=aquacrop_fd

after_success:
  - codecov

notifications:
  email: false
