name: aquacrop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - numpy
  - rasterio>=1.0
  - xarray
  - pandas
  - dask
  - netcdf4
  - scipy
  - shapely
  - click
  - pip:
    - -e .
    - python-dateutil
